application: scormcloudapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /gadgets
  static_dir: gadgets

- url: /cron/reminders
  script: cron/reminders.py
  login: admin

- url: /cron/autoexpire
  script: cron/autoexpire.py
  login: admin

- url: /.*
  script: main.py
